#include "PresetBrowser.h"

namespace vstengine::ui {
PresetBrowser::PresetBrowser (vstengine::PresetManager& m,
                              std::function<void()> loaded)
    : manager (m), onPresetLoaded (std::move (loaded))
{
    for (auto* b : { &factoryButton,&userButton,&loadButton,&saveButton,&saveFullButton,&renameButton,&deleteButton,&refreshButton }) { styleButton(*b); addAndMakeVisible(*b); }
    styleButton(loadButton,true); factoryButton.onClick=[this]{category.setSelectedId(5,juce::sendNotificationSync);}; userButton.onClick=[this]{category.setSelectedId(4,juce::sendNotificationSync);};
    loadButton.onClick=[this]{load();}; saveButton.onClick=[this]{save(false);};saveFullButton.onClick=[this]{save(true);};renameButton.onClick=[this]{rename();};deleteButton.onClick=[this]{remove();};refreshButton.onClick=[this]{refresh();};
    search.setTextToShowWhenEmpty("Search presets",colours::mutedText);search.onTextChange=[this]{rebuildFilter();};name.setTextToShowWhenEmpty("Preset name",colours::mutedText);
    category.addItemList({"ALL","BASS","FULL","USER","FACTORY"},1);category.setSelectedId(1);category.onChange=[this]{rebuildFilter();};
    soundEngine.addItem("Save Bass sound",1);soundEngine.setSelectedId(1);
    for(auto*c:{static_cast<juce::Component*>(&search),static_cast<juce::Component*>(&name),static_cast<juce::Component*>(&category),static_cast<juce::Component*>(&soundEngine),static_cast<juce::Component*>(&list),static_cast<juce::Component*>(&type),static_cast<juce::Component*>(&status)})addAndMakeVisible(c);
    styleLabel(type,13,juce::Justification::centredLeft,colours::primary);styleLabel(status,12,juce::Justification::centredLeft,colours::mutedText);refresh();
}
namespace { juce::String categoryOf(const vstengine::PresetManager::PresetEntry&e){using M=vstengine::PresetManager;if(e.kind==M::PresetKind::full)return"Full";if(e.engine==M::SoundEngine::bass)return"Bass";return"Sound";} }
void PresetBrowser::refresh(){all.clear();for(const auto&e:manager.getPresets())all.push_back(e);status.setText("Preset directory refreshed.",juce::dontSendNotification);rebuildFilter();}
void PresetBrowser::rebuildFilter(){filtered.clear();const auto q=search.getText().trim(),filter=category.getText();for(const auto&e:all){if(q.isNotEmpty()&&!e.name.containsIgnoreCase(q))continue;if(filter=="BASS"&&categoryOf(e)!="Bass")continue;if(filter=="FULL"&&categoryOf(e)!="Full")continue;if(filter=="USER"&&e.source!=vstengine::PresetManager::PresetSource::user)continue;if(filter=="FACTORY"&&e.source!=vstengine::PresetManager::PresetSource::factory)continue;filtered.push_back(e);}factoryButton.setToggleState(filter=="FACTORY",juce::dontSendNotification);userButton.setToggleState(filter=="USER",juce::dontSendNotification);list.updateContent();list.selectRow(-1);selectedRowsChanged(-1);}
void PresetBrowser::paintListBoxItem(int row,juce::Graphics&g,int w,int h,bool selected){if(row<0||row>=(int)filtered.size())return;g.fillAll(selected?colours::primary.darker(.65f):(row%2?colours::panel:colours::panelRaised));g.setColour(colours::text);g.setFont(14);g.drawText(filtered[(size_t)row].name,12,0,w-120,h,juce::Justification::centredLeft);g.setColour(colours::mutedText);g.drawText(categoryOf(filtered[(size_t)row]),w-110,0,98,h,juce::Justification::centredRight);}
void PresetBrowser::selectedRowsChanged(int row){const bool valid=row>=0&&row<(int)filtered.size(),user=valid&&!filtered[(size_t)row].isReadOnly();loadButton.setEnabled(valid);renameButton.setEnabled(user);deleteButton.setEnabled(user);if(valid){const auto&e=filtered[(size_t)row];type.setText((e.isReadOnly()?"Factory / ":"User / ")+categoryOf(e),juce::dontSendNotification);name.setText(e.name,false);}else type.setText("ALL / BASS / FULL / USER / FACTORY",juce::dontSendNotification);}
void PresetBrowser::load(){const int row=list.getSelectedRow();if(row<0||row>=(int)filtered.size())return;const auto&e=filtered[(size_t)row];const auto result=manager.loadPreset(e);status.setText(result.wasOk()?"Loaded: "+e.name:result.message,juce::dontSendNotification);if(result&&onPresetLoaded)onPresetLoaded();}
void PresetBrowser::save(bool full){const auto n=name.getText().trim();const auto result=full?manager.saveFullPreset(n):manager.saveSoundPreset(n,vstengine::PresetManager::SoundEngine::bass);if(result){source=vstengine::PresetManager::PresetSource::user;refresh();}status.setText(result.wasOk()?"Saved: "+n:result.message,juce::dontSendNotification);}
void PresetBrowser::rename(){const int row=list.getSelectedRow();if(row<0||row>=(int)filtered.size())return;const auto newName=name.getText().trim();const auto result=manager.renamePreset(filtered[(size_t)row],newName);if(result)refresh();status.setText(result.wasOk()?"Renamed: "+newName:result.message,juce::dontSendNotification);}
void PresetBrowser::remove(){const int row=list.getSelectedRow();if(row<0||row>=(int)filtered.size()||filtered[(size_t)row].isReadOnly())return;const auto n=filtered[(size_t)row].name;const auto result=manager.deletePreset(filtered[(size_t)row]);if(result)refresh();status.setText(result.wasOk()?"Deleted: "+n:result.message,juce::dontSendNotification);}
void PresetBrowser::paint(juce::Graphics&g){g.fillAll(colours::background);g.setColour(colours::panel);g.fillRoundedRectangle(8,8,174.0f,(float)getHeight()-16,8);}
void PresetBrowser::resized(){auto a=getLocalBounds().reduced(16);auto side=a.removeFromLeft(158);factoryButton.setBounds(side.removeFromTop(38).reduced(2));userButton.setBounds(side.removeFromTop(38).reduced(2));side.removeFromTop(12);type.setBounds(side.removeFromTop(48));soundEngine.setBounds(side.removeFromTop(34).reduced(2));a.removeFromLeft(16);auto top=a.removeFromTop(34);search.setBounds(top.removeFromLeft(260).reduced(2));category.setBounds(top.removeFromLeft(150).reduced(2));name.setBounds(top.reduced(2));a.removeFromTop(8);auto bottom=a.removeFromBottom(72);list.setBounds(a);auto buttons=bottom.removeFromTop(36);juce::FlexBox row;row.flexDirection=juce::FlexBox::Direction::row;for(auto*b:{&loadButton,&saveButton,&saveFullButton,&renameButton,&deleteButton,&refreshButton})row.items.add(juce::FlexItem(*b).withFlex(1).withMargin(2));row.performLayout(buttons);status.setBounds(bottom.reduced(4));}
} // namespace vstengine::ui
