#include "SettingsPanel.h"

namespace vstengine::ui {
SettingsPanel::MidiDragButton::MidiDragButton(std::function<juce::File()> fn):juce::TextButton("DRAG MIDI TO CUBASE"),createFile(std::move(fn)){styleButton(*this);}
void SettingsPanel::MidiDragButton::mouseDown(const juce::MouseEvent&e){started=false;juce::TextButton::mouseDown(e);} void SettingsPanel::MidiDragButton::mouseDrag(const juce::MouseEvent&e){juce::TextButton::mouseDrag(e);if(started||e.getDistanceFromDragStart()<6||!createFile)return;const auto f=createFile();if(!f.existsAsFile())return;started=true;juce::StringArray files;files.add(f.getFullPathName());juce::DragAndDropContainer::performExternalDragDropOfFiles(files,false,this);}
SettingsPanel::SettingsPanel(juce::AudioProcessorValueTreeState&s,juce::MidiKeyboardState&ks,Callbacks cb):dragButton(std::move(cb.createMidiFile)),keyboard(ks,juce::MidiKeyboardComponent::horizontalKeyboard)
{
    midiTitle.setText("MIDI",juce::dontSendNotification);generatorTitle.setText("GENERATOR",juce::dontSendNotification);systemTitle.setText("SYSTEM",juce::dontSendNotification);for(auto*l:{&midiTitle,&generatorTitle,&systemTitle}){styleLabel(*l,13,juce::Justification::centredLeft,colours::primary);addAndMakeVisible(*l);}bassChannel.setText("Bass MIDI Channel   1 (Part 1)",juce::dontSendNotification);status.setText("Panic sends explicit safety reset.",juce::dontSendNotification);for(auto*l:{&bassChannel,&status}){styleLabel(*l,13,juce::Justification::centredLeft,colours::mutedText);addAndMakeVisible(*l);}
    for(auto pair:{std::pair<juce::Label*,const char*>{&midiSourceLabel,"MIDI Source"},{&generatorChannelLabel,"Generator MIDI Channel"},{&kickChannelLabel,"Kick MIDI Channel"},{&rootNoteLabel,"Root Note"},{&seedLabel,"Generator Seed"}}){pair.first->setText(pair.second,juce::dontSendNotification);styleLabel(*pair.first,12,juce::Justification::centredLeft,colours::mutedText);addAndMakeVisible(*pair.first);}
    midiMode.addItemList({"AUTO","PIANO ROLL","GENERATOR","BOTH"},1);addAndMakeVisible(midiMode);for(auto*sl:{&generatorChannel,&kickChannel,&rootNote,&seed}){sl->setSliderStyle(juce::Slider::LinearHorizontal);sl->setTextBoxStyle(juce::Slider::TextBoxRight,false,70,22);addAndMakeVisible(sl);}generatorChannel.setName("Generator MIDI Channel");kickChannel.setName("Kick MIDI Channel");rootNote.setName("Root Note");seed.setName("Generator Seed");
    addAndMakeVisible(dragButton);addAndMakeVisible(keyboard);styleButton(panicButton);panicButton.setColour(juce::TextButton::buttonColourId,colours::warning.darker(.45f));panicButton.onClick=std::move(cb.panic);addAndMakeVisible(panicButton);
    modeAttachment=std::make_unique<CA>(s,"midiMode",midiMode);attachments[0]=std::make_unique<SA>(s,"midiChannel",generatorChannel);attachments[1]=std::make_unique<SA>(s,"kickMidiChannel",kickChannel);attachments[2]=std::make_unique<SA>(s,"rootNote",rootNote);attachments[3]=std::make_unique<SA>(s,"rngSeed",seed);
}
void SettingsPanel::paint(juce::Graphics&g){g.fillAll(colours::background);g.setColour(colours::panel);const auto w=(getWidth()-40)/3;for(int i=0;i<3;++i)g.fillRoundedRectangle((float)(12+i*(w+8)),12,(float)w,(float)getHeight()-150,8);}
void SettingsPanel::resized(){auto a=getLocalBounds().reduced(24);auto keyboardArea=a.removeFromBottom(104);keyboard.setBounds(keyboardArea.removeFromBottom(76));dragButton.setBounds(keyboardArea.removeFromLeft(230).reduced(2));const int w=(a.getWidth()-16)/3;auto midi=a.removeFromLeft(w).reduced(12);a.removeFromLeft(8);auto gen=a.removeFromLeft(w).reduced(12);a.removeFromLeft(8);auto sys=a.reduced(12);midiTitle.setBounds(midi.removeFromTop(28));midiSourceLabel.setBounds(midi.removeFromTop(20));midiMode.setBounds(midi.removeFromTop(34));midi.removeFromTop(12);bassChannel.setBounds(midi.removeFromTop(30));kickChannelLabel.setBounds(midi.removeFromTop(20));kickChannel.setBounds(midi.removeFromTop(40));generatorTitle.setBounds(gen.removeFromTop(28));generatorChannelLabel.setBounds(gen.removeFromTop(20));generatorChannel.setBounds(gen.removeFromTop(40));rootNoteLabel.setBounds(gen.removeFromTop(20));rootNote.setBounds(gen.removeFromTop(40));seedLabel.setBounds(gen.removeFromTop(20));seed.setBounds(gen.removeFromTop(40));systemTitle.setBounds(sys.removeFromTop(28));panicButton.setBounds(sys.removeFromTop(42));status.setBounds(sys.removeFromTop(42));}
} // namespace vstengine::ui
